/**
 * Microsoft themes based on official Microsoft 365 color palettes
 * These match the SharePoint theme presets
 * https://learn.microsoft.com/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-json-schema#teal-theme
 */
import type { ITheme, IThemePalette } from '../types';

/*
  To pull theme values directly from the SharePoint page, paste this in the console:
  const keys = ['themeDarker','themeDark','themeDarkAlt','themePrimary','themeSecondary','themeTertiary','themeLight','themeLighter','themeLighterAlt','black','neutralDark','neutralPrimary','neutralPrimaryAlt','neutralSecondary','neutralTertiary','neutralTertiaryAlt','neutralLight','neutralLighter','neutralLighterAlt','white','neutralQuaternaryAlt','neutralQuaternary','neutralSecondaryAlt','primaryBackground','primaryText','bodyBackground','bodyText','disabledBackground','disabledText','error','accent'];const theme = Object.fromEntries(keys.map(k => [k, __themeState__.theme[k]])); console.log(theme);console.log(__themeState__.theme.backgroundImageUri);

  To find which theme values have specific values, from the SharePoint page, paste this in the console:
  const find='#650e08';console.log("Matching theme keys ("+find+"):",Object.keys(__themeState__.theme).filter(key => __themeState__.theme[key] && __themeState__.theme[key].toString().toLowerCase() === find.toLowerCase()));
*/

const microsoftPalettes: Record<string, IThemePalette> = {
  Teal: {
    themeDarker: '#014446',
    themeDark: '#025c5f',
    themeDarkAlt: '#026d70',
    themePrimary: '#03787C',
    themeSecondary: '#13898d',
    themeTertiary: '#49aeb1',
    themeLight: '#98d6d8',
    themeLighter: '#c5e9ea',
    themeLighterAlt: '#f0f9fa',
    black: '#000000',
    neutralDark: '#201f1e',
    neutralPrimary: '#323130',
    neutralPrimaryAlt: '#3b3a39',
    neutralSecondary: '#605e5c',
    neutralTertiary: '#a19f9d',
    neutralTertiaryAlt: '#c8c8c8',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    white: '#ffffff',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#ffffff',
    primaryText: '#323130',
    bodyBackground: '#ffffff',
    bodyText: '#323130',
    disabledBackground: '#f4f4f4',
    disabledText: '#a19f9d',
    accent: '#03787C',
  },
  Blue: {
    themeDarker: '#0a3965',
    themeDark: '#0e4e8a',
    themeDarkAlt: '#105ca3',
    themePrimary: '#1267B5',
    themeSecondary: '#2875be',
    themeTertiary: '#619cd3',
    themeLight: '#aacae9',
    themeLighter: '#d0e2f3',
    themeLighterAlt: '#f3f8fc',
    black: '#000000',
    neutralDark: '#201f1e',
    neutralPrimary: '#323130',
    neutralPrimaryAlt: '#3b3a39',
    neutralSecondary: '#605e5c',
    neutralTertiary: '#a19f9d',
    neutralTertiaryAlt: '#c8c8c8',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    white: '#ffffff',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#ffffff',
    primaryText: '#323130',
    bodyBackground: '#ffffff',
    bodyText: '#323130',
    disabledBackground: '#f4f4f4',
    disabledText: '#a19f9d',
    accent: '#1267B5',
  },
  Orange: {
    themeDarker: '#5d2509',
    themeDark: '#7e320d',
    themeDarkAlt: '#953c0f',
    themePrimary: '#A74411',
    themeSecondary: '#b05325',
    themeTertiary: '#c9815d',
    themeLight: '#e4bba7',
    themeLighter: '#f1dace',
    themeLighterAlt: '#fbf5f2',
    black: '#000000',
    neutralDark: '#201f1e',
    neutralPrimary: '#323130',
    neutralPrimaryAlt: '#3b3a39',
    neutralSecondary: '#605e5c',
    neutralTertiary: '#a19f9d',
    neutralTertiaryAlt: '#c8c8c8',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    white: '#ffffff',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#ffffff',
    primaryText: '#323130',
    bodyBackground: '#ffffff',
    bodyText: '#323130',
    disabledBackground: '#f4f4f4',
    disabledText: '#a19f9d',
    accent: '#A74411',
  },
  Red: {
    themeDarker: '#612120',
    themeDark: '#842d2b',
    themeDarkAlt: '#9c3533',
    themePrimary: '#AD3A39',
    themeSecondary: '#b74d4b',
    themeTertiary: '#ce7d7b',
    themeLight: '#e7b9b8',
    themeLighter: '#f2d8d8',
    themeLighterAlt: '#fcf5f5',
    black: '#000000',
    neutralDark: '#201f1e',
    neutralPrimary: '#323130',
    neutralPrimaryAlt: '#3b3a39',
    neutralSecondary: '#605e5c',
    neutralTertiary: '#a19f9d',
    neutralTertiaryAlt: '#c8c8c8',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    white: '#ffffff',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#ffffff',
    primaryText: '#323130',
    bodyBackground: '#ffffff',
    bodyText: '#323130',
    disabledBackground: '#f4f4f4',
    disabledText: '#a19f9d',
    accent: '#AD3A39',
  },
  Purple: {
    themeDarker: '#403057',
    themeDark: '#574176',
    themeDarkAlt: '#674d8c',
    themePrimary: '#72559B',
    themeSecondary: '#8165a7',
    themeTertiary: '#a58fc3',
    themeLight: '#cfc3e1',
    themeLighter: '#e5deef',
    themeLighterAlt: '#f8f7fb',
    black: '#000000',
    neutralDark: '#201f1e',
    neutralPrimary: '#323130',
    neutralPrimaryAlt: '#3b3a39',
    neutralSecondary: '#605e5c',
    neutralTertiary: '#a19f9d',
    neutralTertiaryAlt: '#c8c8c8',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    white: '#ffffff',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#ffffff',
    primaryText: '#323130',
    bodyBackground: '#ffffff',
    bodyText: '#323130',
    disabledBackground: '#f4f4f4',
    disabledText: '#a19f9d',
    accent: '#72559B',
  },
  Green: {
    themeDarker: '#254205',
    themeDark: '#335907',
    themeDarkAlt: '#3c6a08',
    themePrimary: '#437509',
    themeSecondary: '#538619',
    themeTertiary: '#80ac4d',
    themeLight: '#bad69b',
    themeLighter: '#d9e9c7',
    themeLighterAlt: '#f5f9f0',
    black: '#000000',
    neutralDark: '#201f1e',
    neutralPrimary: '#323130',
    neutralPrimaryAlt: '#3b3a39',
    neutralSecondary: '#605e5c',
    neutralTertiary: '#a19f9d',
    neutralTertiaryAlt: '#c8c8c8',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    white: '#ffffff',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#ffffff',
    primaryText: '#323130',
    bodyBackground: '#ffffff',
    bodyText: '#323130',
    disabledBackground: '#f4f4f4',
    disabledText: '#a19f9d',
    accent: '#437509',
  },
  Periwinkle: {
    themeDarker: '#333557',
    themeDark: '#464776',
    themeDarkAlt: '#53558c',
    themePrimary: '#5B5D9B',
    themeSecondary: '#6b6da7',
    themeTertiary: '#9395c3',
    themeLight: '#c5c6e1',
    themeLighter: '#dfe0ef',
    themeLighterAlt: '#f7f7fb',
    black: '#000000',
    neutralDark: '#201f1e',
    neutralPrimary: '#323130',
    neutralPrimaryAlt: '#3b3a39',
    neutralSecondary: '#605e5c',
    neutralTertiary: '#a19f9d',
    neutralTertiaryAlt: '#c8c8c8',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    white: '#ffffff',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#ffffff',
    primaryText: '#323130',
    bodyBackground: '#ffffff',
    bodyText: '#323130',
    disabledBackground: '#f4f4f4',
    disabledText: '#a19f9d',
    accent: '#5B5D9B',
  },
  Cobalt: {
    themeDarker: '#1e3472',
    themeDark: '#28479b',
    themeDarkAlt: '#3054b8',
    themePrimary: '#355DCD',
    themeSecondary: '#496ed2',
    themeTertiary: '#7d97e0',
    themeLight: '#bac9f0',
    themeLighter: '#dae1f7',
    themeLighterAlt: '#f5f7fd',
    black: '#000000',
    neutralDark: '#201f1e',
    neutralPrimary: '#323130',
    neutralPrimaryAlt: '#3b3a39',
    neutralSecondary: '#605e5c',
    neutralTertiary: '#a19f9d',
    neutralTertiaryAlt: '#c8c8c8',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    white: '#ffffff',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#ffffff',
    primaryText: '#323130',
    bodyBackground: '#ffffff',
    bodyText: '#323130',
    disabledBackground: '#f4f4f4',
    disabledText: '#a19f9d',
    accent: '#355DCD',
  },
  'Dark Teal': {
    themeDarker: '#94d2d4',
    themeDark: '#74c2c5',
    themeDarkAlt: '#60b7ba',
    themePrimary: '#51AEB2',
    themeSecondary: '#489a9d',
    themeTertiary: '#31696b',
    themeLight: '#193536',
    themeLighter: '#0d1c1d',
    themeLighterAlt: '#030707',
    black: '#f8f8f8',
    neutralDark: '#f4f4f4',
    neutralPrimary: '#ffffff',
    neutralPrimaryAlt: '#dadada',
    neutralSecondary: '#d0d0d0',
    neutralTertiary: '#c8c8c8',
    neutralTertiaryAlt: '#747474',
    neutralLight: '#484848',
    neutralLighter: '#3a3a3a',
    neutralLighterAlt: '#323232',
    white: '#292929',
    neutralQuaternaryAlt: '#505050',
    neutralQuaternary: '#575757',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#292929',
    primaryText: '#ffffff',
    bodyBackground: '#292929',
    bodyText: '#ffffff',
    disabledBackground: '#3a3a3a',
    disabledText: '#c8c8c8',
    accent: '#51AEB2',
  },
  'Dark Blue': {
    themeDarker: '#9cc9f8',
    themeDark: '#7ab6f5',
    themeDarkAlt: '#63a9f4',
    themePrimary: '#529FF1',
    themeSecondary: '#488cd5',
    themeTertiary: '#316091',
    themeLight: '#193049',
    themeLighter: '#0d1a27',
    themeLighterAlt: '#03060a',
    black: '#f8f8f8',
    neutralDark: '#f4f4f4',
    neutralPrimary: '#ffffff',
    neutralPrimaryAlt: '#dadada',
    neutralSecondary: '#d0d0d0',
    neutralTertiary: '#c8c8c8',
    neutralTertiaryAlt: '#747474',
    neutralLight: '#484848',
    neutralLighter: '#3a3a3a',
    neutralLighterAlt: '#323232',
    white: '#292929',
    neutralQuaternaryAlt: '#505050',
    neutralQuaternary: '#575757',
    neutralSecondaryAlt: '#8a8886',
    primaryBackground: '#292929',
    primaryText: '#ffffff',
    bodyBackground: '#292929',
    bodyText: '#ffffff',
    disabledBackground: '#3a3a3a',
    disabledText: '#c8c8c8',
    accent: '#529FF1',
  },
};

export const MICROSOFT_THEMES: ITheme[] = [
  {
    name: 'Teal',
    isInverted: false,
    backgroundImageUri: 'none',
  },
  {
    name: 'Blue',
    isInverted: false,
    backgroundImageUri: 'none',
  },
  {
    name: 'Orange',
    isInverted: false,
    backgroundImageUri: 'none',
  },
  {
    name: 'Red',
    isInverted: false,
    backgroundImageUri: 'none',
  },
  {
    name: 'Purple',
    isInverted: false,
    backgroundImageUri: 'none',
  },
  {
    name: 'Green',
    isInverted: false,
    backgroundImageUri: 'none',
  },
  {
    name: 'Periwinkle',
    isInverted: false,
    backgroundImageUri: 'none',
  },
  {
    name: 'Cobalt',
    isInverted: false,
    backgroundImageUri: 'none',
  },
  {
    name: 'Dark Teal',
    isInverted: true,
    backgroundImageUri: 'none',
  },
  {
    name: 'Dark Blue',
    isInverted: true,
    backgroundImageUri: 'none',
  },
].map((theme) => ({
  ...theme,
  palette: microsoftPalettes[theme.name],
  isCustom: false,
}));
