/**
 * Microsoft themes based on official Microsoft 365 color palettes
 * These match the SharePoint theme presets
 */
import type { ITheme } from '../types';

export const MICROSOFT_THEMES: ITheme[] = [
  {
    id: 'teal',
    name: 'Teal',
    isCustom: false,
    palette: {
      themePrimary: '#03787C',
      themeLighterAlt: '#f0f9fa',
      themeLighter: '#c5e9ea',
      themeLight: '#98d6d8',
      themeTertiary: '#49aeb1',
      themeSecondary: '#13898d',
      themeDarkAlt: '#026d70',
      themeDark: '#025c5f',
      themeDarker: '#014446',
      neutralLighterAlt: '#f8f8f8',
      neutralLighter: '#f4f4f4',
      neutralLight: '#eaeaea',
      neutralQuaternaryAlt: '#dadada',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c8c8',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'blue',
    name: 'Blue',
    isCustom: false,
    palette: {
      themePrimary: '#0078d4',
      themeLighterAlt: '#eff6fc',
      themeLighter: '#deecf9',
      themeLight: '#c7e0f4',
      themeTertiary: '#71afe5',
      themeSecondary: '#2b88d8',
      themeDarkAlt: '#106ebe',
      themeDark: '#005a9e',
      themeDarker: '#004578',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'orange',
    name: 'Orange',
    isCustom: false,
    palette: {
      themePrimary: '#ca5010',
      themeLighterAlt: '#fdf5f0',
      themeLighter: '#f8e0d6',
      themeLight: '#f2c8b8',
      themeTertiary: '#e49471',
      themeSecondary: '#d5652e',
      themeDarkAlt: '#b3480e',
      themeDark: '#953d0c',
      themeDarker: '#6e2d09',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'red',
    name: 'Red',
    isCustom: false,
    palette: {
      themePrimary: '#d13438',
      themeLighterAlt: '#fdf4f4',
      themeLighter: '#f9dada',
      themeLight: '#f4bcbc',
      themeTertiary: '#e77a7b',
      themeSecondary: '#db4749',
      themeDarkAlt: '#bc2f32',
      themeDark: '#9e272a',
      themeDarker: '#751d1f',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'purple',
    name: 'Purple',
    isCustom: false,
    palette: {
      themePrimary: '#5c2d91',
      themeLighterAlt: '#f6f1fb',
      themeLighter: '#e3d7f3',
      themeLight: '#cdb9ea',
      themeTertiary: '#9f7acb',
      themeSecondary: '#7642ac',
      themeDarkAlt: '#532884',
      themeDark: '#46226f',
      themeDarker: '#341a52',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'green',
    name: 'Green',
    isCustom: false,
    palette: {
      themePrimary: '#107c10',
      themeLighterAlt: '#f0faf0',
      themeLighter: '#d6f0d6',
      themeLight: '#b8e4b8',
      themeTertiary: '#6cc86c',
      themeSecondary: '#2ea82e',
      themeDarkAlt: '#0e700e',
      themeDark: '#0b5c0b',
      themeDarker: '#084508',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'periwinkle',
    name: 'Periwinkle',
    isCustom: false,
    palette: {
      themePrimary: '#6b69d6',
      themeLighterAlt: '#f6f6fc',
      themeLighter: '#e0e0f7',
      themeLight: '#c7c6f1',
      themeTertiary: '#9492e3',
      themeSecondary: '#6f6cd7',
      themeDarkAlt: '#605fc1',
      themeDark: '#504fa2',
      themeDarker: '#3b3977',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    isCustom: false,
    palette: {
      themePrimary: '#004e8c',
      themeLighterAlt: '#f0f6fb',
      themeLighter: '#c7dff1',
      themeLight: '#9dc6e5',
      themeTertiary: '#4a94c9',
      themeSecondary: '#0f6ead',
      themeDarkAlt: '#00467e',
      themeDark: '#003b6a',
      themeDarker: '#002b4e',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'dark-teal',
    name: 'Dark Teal',
    isCustom: false,
    palette: {
      themePrimary: '#004b50',
      themeLighterAlt: '#eef8f8',
      themeLighter: '#c6e6e6',
      themeLight: '#9cd2d2',
      themeTertiary: '#4fa7a8',
      themeSecondary: '#15797c',
      themeDarkAlt: '#004347',
      themeDark: '#00373b',
      themeDarker: '#00282b',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
  {
    id: 'dark-blue',
    name: 'Dark Blue',
    isCustom: false,
    palette: {
      themePrimary: '#002050',
      themeLighterAlt: '#f0f3f8',
      themeLighter: '#c7d1e6',
      themeLight: '#9caecc',
      themeTertiary: '#4b6a99',
      themeSecondary: '#0f2f66',
      themeDarkAlt: '#001c48',
      themeDark: '#00173c',
      themeDarker: '#00102b',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  },
];
